### ISSUE TITLE
Beerjs #1

### ISSUE THREAD

**Issue by yoshuawuyts** [beerjs/amsterdam#1]
Let's talk about Beerjs numero uno! We should probably establish the following things before we announce anything:
- [ ] location
- [x] date
- [ ] sponsors?
- [x] meetup group
- [ ] promotion
#### Location

I'm not sure how many people will come, but 20 - 80 people sounds like a fair (and broad) estimate. Besides that the place should have good beer, and if possible be non-cheesy. The hangar you talked about sounded nice, do you have a link?
#### Date

For me date / time is not as much a problem, though I'm not sure how your schedule is. Besides that we should also consider weekdays vs weekends to host the event.
#### Sponsors(?)

Because getting money = free beer for folks. Maybe we could ask CloudNine / Booking to shower us in money which in turn we convert into cool beverages for the attendees.
#### Meetup group

We should probably have one.
#### Promotion

Because no attendees is not good :'(

**Comment by yoshuawuyts** [comment]
Meetup group is made - http://www.meetup.com/beerjs-amsterdam

It could use some flair though, I'll do that later. :)

**Comment by hughsk** [comment]
Perfect :)

The hangar place I mentioned before: http://www.noorderlichtcafe.nl/. Maybe let's check it out some time to see if you reckon it'd be a good location? Not sure how much of a hindrance taking the ferry is for attendees but it's not too far from the ferry stop.

Thursdays/Fridays are good for me :) I'm headed back to Australia October 23 till the beginning of December so we'll probably want to do it before then! Sponsors would be nice too, do you know anybody at booking/cloud9 to ask?

**Comment by junosuarez** [comment]
:beers:

**Comment by yoshuawuyts** [comment]
@hughsk yeah, looks good. Let's go check it out this week. In < 24 h the meetup group will be announced (according to meetup). What do you think of `thu 16/10`?

Oh, and I know nobody at either company's, haha. Got this as a welcome message, hope it's ok-ish:

> Welcome! RSVP if you're interested in attending an upcoming drinkup, and feel free to get in touch if you're interested in getting involved as a sponsor or otherwise.

**Comment by hughsk** [comment]
Sounds good! Gives plenty of time to prepare. I'm free to check the place out any night from tomorrow onwards so whenever works for you :)

**Comment by yoshuawuyts** [comment]
Oh, sure! Let's head out tomorrow then! :D I'm super busy, though I might have to work a little :'( Hope that's ok?

**Comment by hughsk** [comment]
Stale :tada:
