### ISSUE TITLE
Beer.js

### ISSUE THREAD

**Issue by heapwolf** [beerjs/amsterdam#2]
Amsterdam needs a regular Beer.js! 🍻

**Comment by jordanpapaleo** [comment]
Hi!  

I agree. I love Amsterdam.  I actually have been to a few meetups and even threw one out there.

So we have an Amsterdam repo but it may be unsupported.  @0x00A If the current supporters are not active, would you like to become involved and help with organizing meetups?

@hughsk @jbnicolai @yoshuawuyts are you guys doing any sort of events or meetings?  Would you like help or to possible pass on the responsibility for your great city?

Thanks everyone,

Jordan

**Comment by BillieBobbel23** [comment]
If the current supporters are not active anymore I can support you guys for a BeerJS Amsterdam.
Always found it a shame that there hasn't been one yet.

**Comment by heapwolf** [comment]
@jordanpapaleo yeah! 👍 i think @yoshuawuyts is in :sparkles: Berlin :sparkles: these days?

@BillieBobbel23 Let's make it happen! @dominictarr is in town and I've been talking with @jpwesselink about some plans for code + beers so we'll probably all meet tomorrow. /cc @juliangruber

**Comment by jordanpapaleo** [comment]
ok. I added you guys.  At some point in the future, we can remove the others if you want.  Let me know.

Have a beer for me!

**Comment by jpwesselink** [comment]
@jordanpapaleo Thanks! Can you add me as well? :D

**Comment by jpwesselink** [comment]
@BillieBobbel23 We threw one some time ago as after party for Node.js Interactive EU. http://nodeschool.io/amsterdam/nodejs-interactive-europe-2016-beerjs-at-hoppy-days/
